In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from sklearn.neighbors import NearestNeighbors

In [2]:
hw1 = pd.read_csv('homework_1.1.csv')
hw1

,X1,X2,X3,Y
0,-0.440646,-0.390227,0.156718,-0.877671
1,-3.810099,-1.304665,-1.105117,-10.130388
2,-1.425451,-0.340049,1.115908,0.284068
3,-1.325750,0.161906,-0.254670,-1.994344
4,3.120263,1.487343,-1.164839,2.030030
...,...,...,...,...
995,1.281625,-0.062024,-0.109231,1.206058
996,-3.047558,-1.121675,0.678439,-3.229262
997,-0.028757,-0.191722,1.191790,3.160897
998,0.415266,0.373086,1.172636,4.033302


# Question 1

In [3]:
X_hw1 = sm.add_constant(hw1.drop('Y',axis=1))
model = sm.OLS(hw1['Y'], X_hw1).fit()
print("--- Regression ---")
print(model.summary())

--- Regression ---
                            OLS Regression Results                            
Dep. Variable:                      Y   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.991
Method:                 Least Squares   F-statistic:                 3.543e+04
Date:                Fri, 22 May 2026   Prob (F-statistic):               0.00
Time:                        17:27:19   Log-Likelihood:                -727.62
No. Observations:                1000   AIC:                             1463.
Df Residuals:                     996   BIC:                             1483.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0026      0.016 

# Question 2

In [8]:
differences = {}

for xi in hw1.drop('Y',axis=1).columns:
    # Marginal: Y ~ Xi (not fixing others)
    X_single = sm.add_constant(hw1[xi])
    coeff_marginal = sm.OLS(hw1['Y'], X_single).fit().params[xi]
    
    # Partial: Y ~ X1 + X2 + X3 (fixing others)
    coeff_partial = model.params[xi]
    
    differences[xi] = abs(coeff_marginal - coeff_partial)

# Find the Xi with the greatest difference
max_xi = max(differences, key=differences.get)
print('---max---')
print(max_xi)
print(f"The variable with the greatest difference is: {max_xi}")

---max---
X2
The variable with the greatest difference is: X2


In [15]:
hw2 = pd.read_csv('homework_1.2.csv')
X_0 = hw2[hw2['X'] == 0].copy().reset_index(drop=True)
X_1 = hw2[hw2['X'] == 1].copy().reset_index(drop=True)

In [26]:
nn = NearestNeighbors(n_neighbors=1)
nn.fit(X_0[['Z']])
dist, indexs = nn.kneighbors(X_1[['Z']])


print("---distances---")
print(len(dist))
print("---index---")
print(len(indexs))

match_hw2 = X_0.iloc[indexs.flatten()].copy().reset_index(drop=True)
y_1_mean = X_1['Y'].mean()
control_mean = match_hw2['Y'].mean()
effect_mean = y_1_mean - control_mean

print("---Matches---")
print(match_hw2)
print("---max distance---")
print(max(dist))
print()
print("---Effect---")
print(effect_mean)

---distances---
48
---index---
48
---Matches---
    X         Y         Z
0   0  0.716327  0.716327
1   0  0.653108  0.653108
2   0  0.437032  0.437032
3   0  0.778157  0.778157
4   0  0.778157  0.778157
5   0  0.414662  0.414662
6   0  0.778157  0.778157
7   0  0.778157  0.778157
8   0  0.778157  0.778157
9   0  0.778157  0.778157
10  0  0.778157  0.778157
11  0  0.778157  0.778157
12  0  0.466311  0.466311
13  0  0.778157  0.778157
14  0  0.653108  0.653108
15  0  0.778157  0.778157
16  0  0.778157  0.778157
17  0  0.568045  0.568045
18  0  0.616934  0.616934
19  0  0.616934  0.616934
20  0  0.778157  0.778157
21  0  0.670638  0.670638
22  0  0.318569  0.318569
23  0  0.716327  0.716327
24  0  0.131798  0.131798
25  0  0.317983  0.317983
26  0  0.318569  0.318569
27  0  0.568045  0.568045
28  0  0.437032  0.437032
29  0  0.778157  0.778157
30  0  0.158970  0.158970
31  0  0.143353  0.143353
32  0  0.208877  0.208877
33  0  0.414662  0.414662
34  0  0.778157  0.778157
35  0  0.778157 

In [35]:
Z_0 = X_0[['Z']].values
Z_1 = X_1[['Z']].values
nnr = NearestNeighbors(radius=0.2).fit(Z_0)
dist_z, inx = nnr.radius_neighbors(Z_1)
print(f'Lenght of distances: {len(dist_z)}')
print(dist_z)
print()
print(len(inx))

control_y = np.average(X_0['Y'])
mean_y = X_1['Y'].mean()

print(f'Mean: {mean_y - control_y}')

Lenght of distances: 48
[array([0.16637586, 0.11242599, 0.17030618, 0.18629445, 0.14714481,
        0.06296738, 0.19334104, 0.09825537, 0.04842265, 0.0445515 ,
        0.06208104, 0.05885978, 0.02407421, 0.14858791, 0.19194131,
        0.13924287, 0.00113784])
 array([0.09708061, 0.04313074, 0.10101093, 0.11699919, 0.07784955,
        0.13226264, 0.12404579, 0.18974378, 0.02896012, 0.0208726 ,
        0.02474376, 0.00721421, 0.17958334, 0.01043548, 0.17724291,
        0.09336947, 0.07929266, 0.12264606, 0.06994762, 0.07043309])
 array([0.11122629, 0.16517616, 0.10729597, 0.01393241, 0.09130771,
        0.13045735, 0.08426111, 0.02292527, 0.1730316 , 0.01856312,
        0.17934679, 0.00055526, 0.18429561, 0.02872356, 0.19316162,
        0.03106399, 0.15478025, 0.11960403, 0.12901424, 0.17219772,
        0.08566084, 0.13835928, 0.11901826])
 array([0.11361625, 0.15250942, 0.1754458 ]) array([0.18550601])
 array([0.16537199, 0.16144166, 0.04021328, 0.1454534 , 0.18460304,
        0.138406

In [33]:
matches = []
for i, neighbor_indices in enumerate(inx):
    for j, neighbor_idx in enumerate(neighbor_indices):
        origin_idx = X_1.index[i]
        matched_idx = X_0.index[neighbor_idx]
        
        matches.append({
            'X=1_Index': origin_idx,
            'X=1_Z_Value': Z_1[i][0],
            'Matched_X=0_Index': matched_idx,
            'Matched_X=0_Z_Value': Z_0[neighbor_idx][0],
            'Distance': dist_z[i][j]
        })

results_df = pd.DataFrame(matches)
print(results_df)

     X=1_Index  X=1_Z_Value  Matched_X=0_Index  Matched_X=0_Z_Value  Distance
0            0     0.715189                  0             0.548814  0.166376
1            0     0.715189                  1             0.602763  0.112426
2            0     0.715189                  2             0.544883  0.170306
3            0     0.715189                  4             0.528895  0.186294
4            0     0.715189                  5             0.568045  0.147145
..         ...          ...                ...                  ...       ...
732         47     0.828940                 21             0.670638  0.158302
733         47     0.828940                 25             0.653108  0.175832
734         47     0.828940                 31             0.656330  0.172610
735         47     0.828940                 35             0.739264  0.089676
736         47     0.828940                 48             0.716327  0.112613

[737 rows x 5 columns]
